name: Check SQL Files in Pull Request

on:
  pull_request:
    paths:
      - 'scripts/sql/**'

jobs:
  check-sql-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find new SQL files
      id: find-sql-files
      run: |
          git diff main HEAD
