name: 'SQL folder misconfiguration checker'
on:
  pull_request:
    paths:
      - 'scripts/sql/*' # Specify the path to your SQL folder

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Files
      id: check_files
      uses: actions/checkout@v2
      
    - name: Check File Notation
      run: |
        cd scripts/sql
        ls -a 
        echo "==============="
        git diff --name-only
        echo "==============="
        git diff origin/master HEAD


