name: Test workflow

on:
  pull_request:
    branches: [main]
    types: [opened]
    paths:
      - 'scripts/sql/*' # Specify the path to your SQL folder
jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
        
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2        
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        env: 
          pr_no: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GH_TOKEN
          git fetch origin main
          git diff origin/main...HEAD --name-only > mydiff
          echo "mydiff = "
          cat mydiff
          echo "==============="
          file_list=$(git diff origin/main..HEAD --name-only | grep '^scripts/sql/')
          echo "==============="
          for filename in $file_list; do
            echo "File: $filename"
            if [[ "$filename" =~ \.(up|down)\.sql$ ]]; then
              echo "File name is in the correct format: $filename"
            else
              echo "File name is not in the correct format: $filename"
              gh pr comment $pr_no --body "The SQL File name is not in the correct format: $filename."
              exit 1 
            fi
            migration_no= $(echo $badal | cut -d "_" -f 1)
            migration_files_of_this_no=$(ls |grep -i $migration_no |wc -l)
            if [[ $migration_files_of_this_no == "2" ]] ; then
              echo "All looks good "
            else 
               echo "migration no is repeted"
               gh pr comment $pr_no --body "The SQL File no is previously correct."
               exit 1
            fi
          done


          
