name: Test workflow

on:
  pull_request:
    branches: [main]
    types: [opened]
    paths:
      - 'scripts/sql/*' # Specify the path to your SQL folder
jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
        
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2        
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: print-diff
        shell: bash
        env: 
          pr_no: ${{ github.event.pull_request.number }}
        run: |
          git fetch origin main
          git diff origin/main...HEAD --name-only > mydiff
          echo "mydiff = "
          cat mydiff
          echo "==============="
          file_list=$(git diff origin/main..HEAD --name-only | grep '^scripts/sql/')
          echo "==============="
          for filename in $file_list; do
            echo "File: $filename"
            if [[ "$filename" =~ \.(up|down)\.sql$ ]]; then
              echo "File name is in the correct format: $filename"
            else
              echo "File name is not in the correct format: $filename"
              gh pr edit $pr_no --add-label "PR:Not-in-corect-sql-format"
              exit 1 
            fi
          done


          
